<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="org.springframework.security.core.context.SecurityContextHolder,
                  org.springframework.security.core.Authentication" %>
<%
    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    String username = "User";
    String contextPath = request.getContextPath();

    String pageTitle = "RGD AI Assistant";
    String pageDescription = "RGD AI Assistant - Ask questions about RGD data";
    String headContent = ""
        + "<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"
        + "<link rel=\"stylesheet\" href=\"" + contextPath + "/resources/css/style.css\"/>\n"
        + "<script src=\"https://cdn.jsdelivr.net/npm/marked/marked.min.js\"></script>\n"
        + "<script type=\"module\">\n"
        + "  import * as smd from 'https://cdn.jsdelivr.net/npm/streaming-markdown/smd.min.js';\n"
        + "  window.smd = smd;\n"
        + "</script>\n"
        + "<script>\n"
        + "  var username = \"" + username + "\";\n"
        + "  var contextPath = \"" + contextPath + "\";\n"
        + "</script>\n"
        + "<script src=\"" + contextPath + "/resources/js/script-openai.js?v=" + System.currentTimeMillis() + "\"></script>\n";
%>
<%@ include file="/common/headerarea.jsp" %>

<div class="chat-container">
    <!-- Upload Modal -->
    <div id="uploadModal" class="modal">
        <div class="modal-content">
            <span class="closeModalSpan">&times;</span>
            <h2>Upload a file to OpenAI</h2>
            <form id="uploadForm" method="post" action="<%= contextPath %>/upload-openai" enctype="multipart/form-data" target="hiddenUploadFrame">
                <input type="file" name="file" id="file" required/>
                <input type="submit" value="Upload" class="submit-btn"/>
            </form>
            <div class="loader" id="loader">
                <div class="loading-spinner"></div>
            </div>
        </div>
    </div>

    <!-- URL Modal -->
    <div id="urlModal" class="modal">
        <div class="modal-content">
            <span class="closeUrlModalSpan">&times;</span>
            <h2>Process Website URL</h2>
            <form id="urlForm">
                <input type="url" name="url" id="urlInput" placeholder="https://example.com" required/>
                <input type="submit" value="Process" class="submit-btn"/>
            </form>
            <div class="loader" id="urlLoader">
                <div class="loading-spinner"></div>
            </div>
        </div>
    </div>

    <iframe name="hiddenUploadFrame" id="hiddenUploadFrame" style="display:none;"></iframe>

    <!-- Chat Area -->
    <div id="chatArea">
        <div id="header">
            <h2>RGD AI Assistant</h2>
        </div>

        <div id="disclaimer">
            <div id="disclaimerHeader">
                <span class="disclaimer-arrow">&#9660;</span>
                <strong>Disclaimer</strong>
            </div>
            <div id="disclaimerContent">
                This AI chatbot provides information from RGD's knowledge base. Responses are generated by AI and should be verified for accuracy.
            </div>
        </div>

        <div id="transcript"></div>
        <div class="start-over-section">
            <button id="startOverBtn" class="start-over-btn">Clear memory</button>
        </div>
        <%if((request.getServerName().equals("localhost"))){%>
        <div id="controls">
            <button id="uploadFile" class="upload-btn">Upload File</button>
            <button id="processUrl" class="upload-btn">Process URL</button>
            <%-- <button id="loadTrials" class="upload-btn">Load Clinical Trials</button> --%>
        </div>
        <%}%>
        <div class="input-area">
            <textarea id="userInput" placeholder="Ask a question..." rows="3"></textarea>
            <button id="typedTextSubmit" class="submit-btn">Send</button>
        </div>
    </div>
</div>

<%@ include file="/common/footerarea.jsp" %>
